/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#465d96",
        "background": "#f7f9ff",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "on-tertiary-container": "#dc6857",
        "on-error": "#ffffff",
        "surface-container": "#e3efff",
        "surface-variant": "#d1e4fb",
        "tertiary-fixed-dim": "#ffb4a9",
        "surface-container-high": "#e6e8ee",
        "surface-bright": "#f7f9ff",
        "secondary-fixed-dim": "#93ccff",
        "on-error-container": "#93000a",
        "tertiary-container": "#510000",
        "surface": "#f7f9ff",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#b2c5ff",
        "on-primary-container": "#7389c7",
        "on-secondary-fixed": "#001d31",
        "inverse-primary": "#b2c5ff",
        "secondary-fixed": "#cce5ff",
        "on-primary-fixed-variant": "#2d457d",
        "surface-dim": "#d8dae0",
        "outline": "#757781",
        "inverse-on-surface": "#eff1f7",
        "tertiary-fixed": "#ffdad4",
        "inverse-surface": "#2d3135",
        "surface-container-highest": "#e0e2e8",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#001847",
        "surface-container-low": "#f1f3f9",
        "on-tertiary-fixed": "#410000",
        "outline-variant": "#c5c6d1",
        "on-secondary-container": "#00517d",
        "secondary-container": "#5cb8fd",
        "primary": "#002058",
        "on-tertiary-fixed-variant": "#83251b",
        "primary-fixed": "#dae2ff",
        "tertiary": "#500000",
        "on-surface-variant": "#444650",
        "on-secondary-fixed-variant": "#004b73",
        "on-surface": "#181c20",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "primary-container": "#1a3673",
        "secondary": "#006397",
        "on-background": "#181c20",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-xs": "4px",
        "space-sm": "8px",
        "space-md": "16px",
        "space-lg": "24px",
        "space-xl": "32px",
        "space-2xl": "48px",
        "space-3xl": "64px",
        "gutter": "24px",
        "container-max": "1280px",
        "base": "8px",
      },
      fontFamily: {
        "display-lg": ["Montserrat", "sans-serif"],
        "display-lg-mobile": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "headline-sm": ["Montserrat", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "body-sm": ["Hanken Grotesk", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
        "label-caps": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "0em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-mono": ["13px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-caps": ["11px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "700" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [require("tailwindcss-rtl")],
}

